apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-eu-02
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  - v1
  resources:
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-eu-02
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: integration-eu-02
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: integration-eu-02

